"""Tests for `hearth migrate generate` (F1 surface)."""

from __future__ import annotations

import importlib
from pathlib import Path

import pytest
from typer.testing import CliRunner

from hearth.cli import app
from hearth.kernel.registry import PluginInfo, Registry


def test_migrate_generate_unknown_plugin_fails(monkeypatch: pytest.MonkeyPatch) -> None:
    """Unknown plugin alias → exit 1 with "not installed" message."""
    monkeypatch.setenv("DATABASE_URL", "sqlite:///:memory:")
    runner = CliRunner()
    result = runner.invoke(app, ["migrate", "generate", "nonexistent_plug"])
    assert result.exit_code == 1, result.output
    assert "not installed" in result.output


def test_migrate_generate_rejects_non_editable(
    tmp_path: object,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """If the plugin's install_path is inside site-packages, abort with help."""
    real_build = Registry.build

    def fake_build() -> Registry:
        reg = real_build()
        reg.plugins["fakeplug"] = PluginInfo(
            alias="fakeplug",
            package="fakeplug",
            version="0.0.1",
            module="fakeplug",
            install_path="/usr/lib/python3.13/site-packages/fakeplug",
            depends_on=[],
            extends=[],
            entities=[],
            actions=[],
            events=[],
        )
        return reg

    monkeypatch.setattr(Registry, "build", staticmethod(fake_build))
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path}/x.db")

    runner = CliRunner()
    result = runner.invoke(app, ["migrate", "generate", "fakeplug"])
    assert result.exit_code == 1, result.output
    assert "not an editable install" in result.output
    assert "pip install -e" in result.output


def test_generate_writes_revision_with_hearth_upgrade_ops(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    tmp_plugin_with_migrations: object,
) -> None:
    """End-to-end: `hearth migrate generate` autogenerates a revision whose
    file contains `HEARTH_UPGRADE_OPS` with a `CreateTable` summary entry."""
    builder = tmp_plugin_with_migrations  # type: ignore[assignment]

    # 1. Define a User entity inside the tmp plugin and re-export it so that
    #    importing the package registers the entity (and its table) in METADATA.
    (builder.package_dir / "entities.py").write_text(
        "from hearth import Entity\n"
        "\n"
        f"class User(Entity, plugin={builder.plugin!r}):\n"
        '    name: str = ""\n'
    )
    (builder.package_dir / "__init__.py").write_text(
        f"from {builder.plugin}.entities import User\n\n__all__ = ['User']\n"
    )

    # Force the module to import so its Entity subclass body runs and the
    # corresponding table is added to METADATA before autogen runs.
    plugin_module = importlib.import_module(builder.plugin)
    user_cls = plugin_module.User

    # 2. Stub Registry.build() to include our tmp plugin. The real `build()`
    #    sets `install_path` to the module's `__file__`, and `_migrate.py`
    #    derives the migrations dir via `os.path.dirname(install_path)`; mirror
    #    that contract so the generated revision lands in the fixture's
    #    migrations/ directory.
    real_build = Registry.build

    def fake_build() -> Registry:
        reg = real_build()
        reg.plugins[builder.plugin] = PluginInfo(
            alias=builder.plugin,
            package=builder.plugin,
            version="0.0.1",
            module=builder.plugin,
            install_path=str(builder.package_dir / "__init__.py"),
            depends_on=[],
            extends=[],
            entities=[user_cls],
            actions=[],
            events=[],
        )
        return reg

    monkeypatch.setattr(Registry, "build", staticmethod(fake_build))
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path}/gen.db")

    # 3. Run the CLI.
    runner = CliRunner()
    result = runner.invoke(app, ["migrate", "generate", builder.plugin])
    assert result.exit_code == 0, result.output

    # 4. Assert the autogenerated revision file carries the post-processed
    #    HEARTH_UPGRADE_OPS with a CreateTable entry for our User table.
    migrations_dir = builder.package_dir / "migrations"
    rev_files = [p for p in migrations_dir.glob("*.py") if p.name != "__init__.py"]
    assert len(rev_files) == 1, [p.name for p in rev_files]
    content = rev_files[0].read_text()
    assert "HEARTH_UPGRADE_OPS" in content
    # `repr()`-formatted string literals use single quotes by default; accept
    # either to stay robust if Python ever changes default quote style.
    assert "kind='CreateTable'" in content or 'kind="CreateTable"' in content
